apiVersion: v1
kind: pod 
metadata: 
  name: aws-cli
  namespace: default
spec:
  serviceAccountName: aws-test
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: [ "/bin/bash", "-c", "--"]
      args: [ "while true; do sleep 30; done;" ]
  tolerations:
    - operator: Exists
      effect: NoSchedule